### ISSUE TITLE
Lab 2, Question 7 

### ISSUE THREAD

**Issue by merima-d** [Watts-College/cpp-526-sum-2024#14]
Can anybody narrow this bit for me please, because it's ambiguous and I am unclear what to use for the denominator?! The instructions for the same question do  not lead to one answer.

From R script : "The first answer is tax-delinquent commercial properties over all commercial properties," vs. "What proportion of commercial properties are delinquent on taxes," in the instruction sheet. Which is it???

**Comment by gmcirco** [comment]
Hi Merima,

The wording might be a bit confusing, but the intention is to find the proportion of commercial properties that are delinquent over all delinquent properties. So:

delinquent commercial properties / all commercial properties
