### ISSUE TITLE
Lab 03 - Visualization

### ISSUE THREAD

**Issue by CTNovoa** [Watts-College/cpp-526-sum-2024#15]
I can't seem to get my x- or y-axis to be labeled to the extent of my range (i.e., 2012 and 9). Any advice on what I made need to do to change this? Right now, using the following, my x-axis labels end at 2000 and my y-axis labels end at 8:

plot.window(xlim = c(1900, 2012), 
            ylim = c(ave.so.min, 
                     ave.so.max))

Thanks for the assistance!

**Comment by CTNovoa** [comment]
Related - the assignment asks to add a subtitle, but when I look up how to add a subtitle in R, I am provided with the function title ( sub = " "), but this adds a title below the x-axis. However, I thought by "add subtitle" the assignment was referring to the following from the NYT's graphic, "There were more strikeouts in 2012 than at any other time in major league history." If so, that text is placed immediately under the main header/title, not beneath the x-axis. What is the function needed to create a "true" subtitle, one that exists under the main title, rather than below the x-axis?

**Comment by gmcirco** [comment]
The 'sub' option places a title at the bottom. You can, however, add additional titles to the top by calling `title` again:

`title( main = "There were more strikeouts in 2012 than at any other time in major league history.", 
      cex.main=0.8, line=-0.4, col.main="gray30", adj=0 )`

This creates a second title. The arguments `cex.main` control the size, `line` controls the location, and `col.main` controls the color. `adj=0` sets the left adjustment to zero, which places it left-aligned.

You can see some references here: https://www.rdocumentation.org/packages/graphics/versions/3.6.2/topics/title

**Comment by CTNovoa** [comment]
Thank you, this worked perfectly! I appreciate the clarification.

**Comment by anaitab** [comment]
Thank you! I used this info also to change the color and size of the axes tick labels.
