### ISSUE TITLE
Lab04 Number of Teams

### ISSUE THREAD

**Issue by CTNovoa** [Watts-College/cpp-526-sum-2024#17]
The assignment reads, "select 10-25 teams, and include their full name in the choices list only once." Thus, I just wanted to verify that we are indeed allowed to select any number within that range and can still receive full credit on the lab. Further, while the NYT visualization depicts 30 unique team names, we are not expected to include all 30; rather, we can include anywhere from 10-25 teams.

Thanks!

**Comment by gmcirco** [comment]
Yep, that is correct. You only need to pick a subset of the full set of teams.
