### ISSUE TITLE
Lab 4

### ISSUE THREAD

**Issue by jsanazaro** [Watts-College/cpp-526-sum-2024#18]
I think I "broke" my shiny app. One minute it was running and now I am getting weird messages like this:

Error:<text>:24:22 unexpected','
23:
24: iputID="my_team",

**Comment by jsanazaro** [comment]
[MyBad.pdf](https://github.com/user-attachments/files/15745042/MyBad.pdf)

**Comment by gmcirco** [comment]
This error is related to something in your code. The highlighted part displays where the error is occuring. It looks like you have a comma after the input on that line, which is causing the error. You can remove the line of code or edit it to try and determine if it is that line, or a line above or below.
