### ISSUE TITLE
I would like to use the DP4SS textbook offline. Is it OK to download it, and how should I download it?

### ISSUE THREAD

**Issue by anaitab** [Watts-College/cpp-526-sum-2024#19]
Hello,
I would appreciate being able to download the full textbook and access it offline. Is there a way to do this?
I clicked the little spider-cat icon labeled "Source Code," which took me to GitHub. There, I found a complicated, long set of folders and files that make up the book, and I could not figure out what to do with them.

Thanks for your help!
Ana

https://ds4ps.org/dp4ss/

Data Programming for the Social Sciences (DP4SS)
A gentle introduction to data programming
in R for social science audiences.
Jesse Lecy
&
Jamison Crawford

**Comment by ngipe7** [comment]
Hi Ana.

This textbook is interactive and has many links to other online sources. I do not believe that this could be downloaded and used in the way it was intended. 

Best,
Nichole

**Comment by gmcirco** [comment]
Hi Ana,

Your best bet would be to reach out to the authors Jesse Lecy or Jamison Crawford and see if they have a fully rendered version.

**Comment by lecy** [comment]
Nichole and Prof Circo are correct - it can't be converted into a book format without breaking the interactive functionality, unfortunately. 

This version is organized more like a book if helpful, but the interactive tutorials are missing: 

https://ds4ps.org/dp4ss/TEXTBOOK/
