### ISSUE TITLE
Lab05_"Accidents by Hour & Age"

### ISSUE THREAD

**Issue by CTNovoa** [Watts-College/cpp-526-sum-2024#20]
The way I am interpreting the provided set-up for this question (see screenshot below) makes me feel as if I am supposed to manually enter in all the correct values, for each applicable row and column, using the c() function. Is this correct?

Of course, I recognize that this means I have to use other functions to discover what the correct values are, but I wanted to check my overall thinking on this. Thanks!

<img width="704" alt="Screenshot 2024-06-12 203412" src="https://github.com/Watts-College/cpp-526-sum-2024/assets/170066212/577766b8-9606-4035-acf6-f5bae60db091">

**Comment by gmcirco** [comment]
Good question here! The displayed table is only an *example* of what the final output should look like. You will need to use `dplyr` verbs to group and aggregate information to generate the necessary columns. If you look at the code block below, you will see that it is partially started. I have added a single line to show you the intended workflow:

```
dat %>% 
  group_by(hour12, age) %>% 
  summarize(n = n()) %>%      # Partial solution
  group_by(age) %>%           # Requires two new variables in 'mutate()'
  mutate(n.age = sum(n))      # Lastly, requires function 'filter()
```

The line `mutate(n.age = sum(n))` creates a new variable named `n.age` and sets its value to the total (sum) of each age group. For example, there are 1458 individuals in the dataset aged 16-18 years old.
