### ISSUE TITLE
Dashboard Final Assignment: Package DT error message

### ISSUE THREAD

**Issue by CTNovoa** [Watts-College/cpp-526-sum-2024#21]
For the final dashboard assignment, I am receiving the following error message:

> library( DT)
Warning: package ‘DT’ was built under R version 4.2.3
Error: package or namespace load failed for ‘DT’ in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]):
 namespace ‘htmltools’ 0.5.4 is already loaded, but >= 0.5.7 is required

Any guidance in terms of next steps here? Thank you!

**Comment by merima-d** [comment]
Hi, Corina have you tried to download a higher version of R perhaps?

**Comment by gmcirco** [comment]
This error suggests there is a version mismatch between one of the installed packages and the DT package. You can try reinstalling the htmltools package like this:

`install.packages("htmltools", dependencies = TRUE)`

and try again.

**Comment by CTNovoa** [comment]
Thank you both for the suggestions! That error has gone away, but now I receive the following error: 
<img width="539" alt="image" src="https://github.com/Watts-College/cpp-526-sum-2024/assets/170066212/3b06f851-f56e-42bf-997c-adb5c523280b">

I have tried updating my dplyr package and really all packages. Any other thoughts on next steps? Unfortunately, I have been unable to get this lab assignment to print.

**Comment by merima-d** [comment]
I believe it is the library issue. Whenever I had this problem I would add needed libraries in the location where other libraries are listed: library(dplyr) and library(magrittr) in case they are not listed. Instead of those, you might try tidyverse because the content of the package overlaps with the former libraries a lot. Updating libraries doesn't mean you are including them automatically for your specific project. At least, this is my understanding. Good luck!

**Comment by CTNovoa** [comment]
Thanks merima-d,
I tried installing all these again and loading them again, but the same error seems to be persisting sadly.

**Comment by merima-d** [comment]
it's a silly observation but is it in the right place in your syntax?

**Comment by CTNovoa** [comment]
I finally was able to get it to knit, I needed to change "r eval = FALSE" up at the top to "r include = FALSE" and then it finally worked. Thank you for all your assistance in troubleshooting. So appreciated.

<img width="407" alt="image" src="https://github.com/Watts-College/cpp-526-sum-2024/assets/170066212/5064fec7-d803-4e37-af1a-30adbe0da904">

**Comment by merima-d** [comment]
Great!






On Friday, June 21, 2024 at 06:24:59 PM EDT, CTNovoa ***@***.***> wrote: 







I finally was able to get it to knit, I needed to change "r eval = FALSE" up at the top to "r include = FALSE" and then it finally worked. Thank you for all your assistance in troubleshooting. So appreciated.
image.png (view on web)
