### ISSUE TITLE
Error when running final dashboard project

### ISSUE THREAD

**Issue by CTNovoa** [Watts-College/cpp-526-sum-2024#23]
When attempting to "run" the final dashboard project I am getting the following error: 
<img width="350" alt="image" src="https://github.com/Watts-College/cpp-526-sum-2024/assets/170066212/b702d12b-fb22-4c77-99cf-9926f2654be1">

I verified that I have the newest version of R Studio and have tried updating to the newest version of R. Thus, I am not sure why this error is popping up...

**Comment by gmcirco** [comment]
Try reinstalling the 'cli' library:

`install.packages("cli")`

**Comment by CTNovoa** [comment]
Hm, I tried that and still seem to be getting the following error:

Error: package or namespace load failed for ‘ggmap’ in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]):
 namespace ‘cli’ 3.6.0 is already loaded, but >= 3.6.1 is required
In addition: Warning message:
package ‘ggmap’ was built under R version 4.2.3 

Thank you for the suggestion and assistance.

**Comment by CTNovoa** [comment]
@gmcirco 
It appears it may be having a similar issue with both tidyverse and ggmap. I have tried installing them again, and "cli," but have not had any luck unfortunately.

**Comment by CTNovoa** [comment]
Okay, I think I resolved this now by following some advice here: https://forum.posit.co/t/rlang-error-on-rstudio-2020-error-package-or-namespace-load-failed-for-in-loadnamespace/79768/4

I first had to intentionally remove the "cli" and "ggmap" packages (with remove.packages) and then install them again. Thank you, @gmcirco!
