### ISSUE TITLE
Lab 6 - Counting total number of players

### ISSUE THREAD

**Issue by rehunkler** [Watts-College/cpp-526-sum-2024#7]
The first question in Lab #6 asks us to find the total number of players. Since playerID is a character variable, I converted it to a numeric. However, this returns "NA", which doesn't allow me to summarize to anything meaningful. I'm trying to convert each playerID into a "1". Any suggestions? Here is my current code below: 

Salaries %>% 
  mutate(salary.adj = salary * (1.03)^(max(yearID) - yearID)) %>%
  group_by(yearID,teamID,playerID) %>% 
  summarise(total.salary = sum(salary.adj)) %>% 
  mutate(players = as.numeric(playerID))

**Comment by lecy** [comment]
There is a count() function, but you can also use n=n() in a summarize function.

https://dplyr.tidyverse.org/reference/count.html
